### ISSUE TITLE
ktask -m raise runtime error

### ISSUE THREAD

**Issue by xrivendell7** [bata24/gef#77] opened 2024-05-10 09:31 UTC
Hello 
When I use `ktask -n -m xx` try to get user thread memory, get this error below

```
gef> ktask -n -m sushi
[+] Wait for memory scan
[+] init_task: 0xffffffff8ce95840
[+] offsetof(task_struct, tasks): 0x4d8
[+] Number of tasks: 294
[+] offsetof(task_struct, mm): 0x528
[+] offsetof(task_struct, stack): 0x20
[+] offsetof(task_struct, pid): 0x5a0
[+] offsetof(task_struct, stack_canary): 0x5a8
[+] offsetof(task_struct, comm): 0x898
[+] offsetof(task_struct, cred): 0x888
[+] offsetof(cred, uid): 0x14

------------------------------- Exception raised -------------------------------
RuntimeError: No active exception to reraise
----------------------------- Detailed stacktrace ------------------------------
File "/home/tomcat/gef/gef.py", line 52521, in __init__()
    ->     raise
File "/home/tomcat/gef/gef.py", line 52695, in get_vm_area_struct()
    ->     get_next_vma_area_struct = self.MapleTree(mm, self.quiet).get_next
File "/home/tomcat/gef/gef.py", line 52733, in get_offset_vm_mm()
    ->     vm_area_struct, _ = self.get_vm_area_struct(mm)
File "/home/tomcat/gef/gef.py", line 53432, in initialize()
    ->     self.offset_vm_mm = self.get_offset_vm_mm(task_addrs, self.offset_mm)
File "/home/tomcat/gef/gef.py", line 53820, in do_invoke()
    ->     ret = self.initialize(args)
File "/home/tomcat/gef/gef.py", line 11016, in wrapper()
    ->     return f(*args, **kwargs)
File "/home/tomcat/gef/gef.py", line 11133, in inner_f()
    ->     return f(*args, **kwargs)
File "/home/tomcat/gef/gef.py", line 11057, in inner_f()
    ->     return f(*args, **kwargs)
File "/home/tomcat/gef/gef.py", line 10966, in wrapper()
    ->     return f(*args, **kwargs)
File "/home/tomcat/gef/gef.py", line 10936, in wrapper()
    ->     return f(self, args, **kwargs)
File "/home/tomcat/gef/gef.py", line 13449, in invoke()
    ->     self.do_invoke(argv)
----------------------------- Last 10 GDB commands -----------------------------
  491  info breakpoints
  492  c
  493  info breakpoints
  494  ktask
  495  ktask -n
  496  kcurrent
  497  ktask -n -m -f 50e
  498  ktask -n -m -f sh
  499  ktask -n -m -f 4608
  500  ktask -n -m
----------------------------- Runtime environment ------------------------------
gdb:     13.1
python:  3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
OS:      Debian GNU/Linux 12 (bookworm)
kernel:  Linux lasvegas 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux
qemu:    7.2.9Debian 1:7.2+dfsg-7+deb12u5
--------------------------------------------------------------------------------

```

**Comment by bata24** [comment] 2024-05-10 11:47
Thank you for reporting.
I didn't expect the pattern to cause RAISE here.

Sorry to trouble you, could you provide this kernel?

**Comment by xrivendell7** [comment] 2024-05-10 12:38
OK!
I upload this [bzimage](https://www.dropbox.com/scl/fi/n10ldjd89c0lcnif5snko/bzImage0510?rlkey=c4fudh0ub0eu7zrf88hm42x8n&st=sxhh8ffp&dl=0) and [vmlinux](https://www.dropbox.com/scl/fi/axw96xh3orhyv5qk1g9px/vmlinux0510?rlkey=0tb4w65fdt3ywjh8zxtpjl0jp&st=3it6hsiy&dl=0).

**Comment by xrivendell7** [comment] 2024-05-10 12:47
and also, the kcurrent seems not work as well
```shell
gef> kcurrent
[+] Wait for memory scan
[+] __per_cpu_offset: 0xffffffff8cbcea40
[+] num of cpu: 9 (guessed)
[+] current_task: 0x1
```

**Comment by bata24** [comment] 2024-05-10 20:47
It seems that it was a small adjustment error in the fixed value.
`ktask -m`, `kcurrent` and `kcmdline` have been fixed.

Also fixed the logic of `kdmesg`, `kpipe` and `kfilesystems` commands.

**Comment by gestapo7** [comment] 2024-05-11 02:05
Hi, seems some command still can't not fully working.

```
gef> kcurrent
[+] Wait for memory scan
[+] __per_cpu_offset: 0xffffffff8cbcea40
[+] num of cpu: 9 (guessed)
[+] current_task: 0x3bcc0
current (cpu0): 0xffffffff8ce95840 swapper/0
current (cpu1): 0xffff888242a69e80 swapper/1
current (cpu2): 0xffff888107241e80 swapper/2
current (cpu3): 0xffff888242a6bcc0 swapper/3
current (cpu4): 0xffff888107243cc0 swapper/4
current (cpu5): 0xffff888242a6db00 swapper/5
current (cpu6): 0xffff888107245b00 swapper/6
current (cpu7): 0xffff888242a70040 swapper/7

------------------------------- Exception raised -------------------------------
MemoryError: Cannot access memory at address 0x10003bcc3
----------------------------- Detailed stacktrace ------------------------------
File "/home/tomcat/gef/gef.py", line 10528, in read_memory()
    ->     return gdb.selected_inferior().read_memory(addr, length).tobytes()
File "/home/tomcat/gef/gef.py", line 10625, in read_int_from_memory()
    ->     mem = read_memory(addr, sz)
File "/home/tomcat/gef/gef.py", line 51604, in dump_current_x86()
    ->     task = read_int_from_memory(cpu_base + task_offset)
File "/home/tomcat/gef/gef.py", line 51633, in do_invoke()
    ->     self.dump_current_x86()
File "/home/tomcat/gef/gef.py", line 11016, in wrapper()
    ->     return f(*args, **kwargs)
File "/home/tomcat/gef/gef.py", line 11133, in inner_f()
    ->     return f(*args, **kwargs)
File "/home/tomcat/gef/gef.py", line 11057, in inner_f()
    ->     return f(*args, **kwargs)
File "/home/tomcat/gef/gef.py", line 10966, in wrapper()
    ->     return f(*args, **kwargs)
File "/home/tomcat/gef/gef.py", line 10936, in wrapper()
    ->     return f(self, args, **kwargs)
File "/home/tomcat/gef/gef.py", line 13449, in invoke()
    ->     self.do_invoke(argv)
----------------------------- Last 10 GDB commands -----------------------------
  266  kcurrent
  267  kcurrent
  268  kcmdline
  269  kdmesg
  270  kdmesg -n
  271  kfilesystems
  272  kfilesystems -n
  273  ktask -n
  274  ktask -n -m -f bash
  275  kcurrent
----------------------------- Runtime environment ------------------------------
gdb:     13.1
python:  3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
OS:      Debian GNU/Linux 12 (bookworm)
kernel:  Linux lasvegas 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux
qemu:    7.2.9Debian 1:7.2+dfsg-7+deb12u5
--------------------------------------------------------------------------------

```

**Comment by bata24** [comment] 2024-05-11 02:18
This behavior was not observed. Could you tell me the start command of QEMU in your environment?
I want to know the `-cpu` and `-smp` options.

**Comment by xrivendell7** [comment] 2024-05-11 02:23
```
#!/bin/sh
qemu-system-x86_64 \
    -gdb tcp::12345 \
    -kernel kernel/arch/x86/boot/bzImage \
    -append "console=ttyS0 root=/dev/sda debug earlyprintk=serial slub_debug=QUZ" \
    -hda 50e.img \
    -net user,hostfwd=tcp:0.0.0.0:31400-:22 -net nic \
    -enable-kvm \
    -cpu host \
    -nographic \
    -m 16G \
    -smp 8 \
    -pidfile vm.pid \
    2>&1 | tee vm.log
```

**Comment by xrivendell7** [comment] 2024-05-11 02:34
aslo, seems `ktask -n -m -f file0` hang here.

```
0xffff88817f2a9e80 K   4625    file0            0xffff888257904c40 [    0,    0] 0xffffc900055e8000 0x09cad2344b4b7900
0xffff88825ec0bcc0 K   4647    krxrpcio/7001    0xffff8882579044c0 [    0,    0] 0xffffc90005488000 0x9dc0fcc42f0dc100
0xffff88825ddb0040 K   4652    kworker/u18:2    0xffff888111b94640 [    0,    0] 0xffffc900055f8000 0xd01ca4f77b626600
0xffff88825ddb1e80 K   4653    kworker/u18:1    0xffff8882579050c0 [    0,    0] 0xffffc900050d0000 0x0e8debf67b8d4f00
gef> ktask -n -m -f file0
[+] Wait for memory scan
[+] init_task: 0xffffffff8ce95840
[+] offsetof(task_struct, tasks): 0x4d8
[+] Number of tasks: 296
[+] offsetof(task_struct, mm): 0x528
[+] offsetof(task_struct, stack): 0x20
[+] offsetof(task_struct, pid): 0x5a0
[+] offsetof(task_struct, stack_canary): 0x5a8
[+] offsetof(task_struct, comm): 0x898
[+] offsetof(task_struct, cred): 0x888
[+] offsetof(cred, uid): 0x14
[+] offsetof(vm_area_struct, vm_mm): 0x10
[+] offsetof(vm_area_struct, vm_flags): 0x20
[+] offsetof(vm_area_struct, vm_file): 0x88


```

**Comment by bata24** [comment] 2024-05-11 03:37
`kcurrent` was fixed.

Fixing `ktask` seems to take more time, so I will do it tonight.
As a workaround, removing `-smp 8` may work fine.

**Comment by xrivendell7** [comment] 2024-05-11 03:41
Hi, really thanks for your quick respone and hard work. 
Since the bug is concurrency, `-smp 8` is required.
Considered maybe KASAN use shadllow memory let gef can't work well, I'll try to disable KASAN and try again.
And I found maybe `slub-dump` can't work well when KASAN is enable, we might be able to work together to fix this vexing problem.
Thanks!

**Comment by bata24** [comment] 2024-05-11 18:31
I have found the cause, but now, I have no idea how to fix it.

~~When `slub_debug=XXX` (in other words, `SLAB_STORE_USER=true` ?) is added to the kernel startup command, some structures about `slub` seems to be different than expected.
Specifically, all free-lists of active/partial/node will be 0.
I think it's managed somewhere else, but I don't know the structure yet.~~

`ktask` and other some commands use `slub-conatins` internally, so I have to solve this problem.

**Comment by bata24** [comment] 2024-05-12 09:54
When `slub_debug=XXX` is enabled, it seems that only `kmem_cache_node` is used instead of `active`/`partial` slabs. And it seems that the cause is that `kmem_cache_node` parsing is failing.

**Comment by bata24** [comment] 2024-05-12 19:46
It was fixed.

The cause was that offset detection of `kmem_cache_node` was failing.
By fixing this, `slub-dump` now works fine.
As a result, `ktask -m` also works correctly now.

Additionally, I also refactored `slub-dump` etc.
- The same `node page` was displayed many times when the CPU number was not specified, so it was displayed only once.
- The `--simple` option is added. This option skips showing layout and free-list.

----

If the `slub_debug=XXX` option is specified to the kernel startup command, the `active`/`partial` slabs will not be used, so please add the `-vv` option each time.

----

~~I found a bug... I am currently fixing it.~~ fixed.

**Comment by xrivendell7** [comment] 2024-05-13 06:33
Oh! Really apperciate.
I'll try.

**Comment by bata24** [comment] 2024-05-17 22:27
Can I close this issue?

**Comment by xrivendell7** [comment] 2024-05-28 01:52
Yeh!

**Closed as completed** 2024-05-28 03:46 UTC
