### ISSUE TITLE
issue getting tcache address

### ISSUE THREAD

**Issue by MrNox** [bata24/gef#95] opened 2024-10-17 12:46 UTC
I found an error getting the tcache address. I'm debugging sshd on ubuntu 22.04 arm64. When I use the command `bins` tcache is empty, `arena.tcachebin(i)` return `None`: https://github.com/bata24/gef/blob/dev/gef.py#L20942.
 
```
for i in range(GlibcHeap.GlibcArena.TCACHE_MAX_BINS):
            chunk = arena.tcachebin(i)
```
I realized that you use the address of `self.heap_base` here: https://github.com/bata24/gef/blob/dev/gef.py#L3774 I think you use it in case you have to get  the address in per thread. I'm not expert, so I don't sure. Anyways in my case it doesn't work.

```
gef> bins
--------------------------- Tcache Bins for arena 'main_arena' ---------------------------
[+] Found 0 valid chunks in tcache.
---------------------------- Fast Bins for arena 'main_arena' ----------------------------
[+] Found 0 valid chunks in fastbins.
-------------------------- Unsorted Bin for arena 'main_arena' --------------------------
[+] Found 0 valid chunks in unsorted bin (when traced from `bk`).
--------------------------- Small Bins for arena 'main_arena' ---------------------------
small_bins[idx=1, size=0x20, @0xfffff7b2bb90]: fd=0xaaaaaacb05e0, bk=0xfffff7b2bb80
 -> Chunk(base=0xaaaaaacb05e0, addr=0xaaaaaacb05f0, size=0x20, flags=PREV_INUSE, fd=0xaaaaaacb0e10, bk=0xfffff7b2bb80 <main_arena+0x70>)
 ```
 
 I saw that there is a symbol called `tcache` and it has the address per thread: https://elixir.bootlin.com/glibc/glibc-2.40/source/malloc/malloc.c#L3125. Then I check gef and pwndbg and use that symbol to obtain the address of tcache, if it fails they do what you have implemented at least in gef.
 
I try to view the tcache and I had this result, and I don't know how to fix it, without gef it works.

```
gef> x/10xg (void*)tcache
value has been optimized out
```
 
 On the other hand, in MallocPar you have this method:
 
 ```
 @property
        def tcache_bins_addr(self):
            if get_libc_version() >= (2, 26):
                return self.sbrk_base_addr + self.char_t.pointer().sizeof
            else:
                return None
 ```
And the tcache address is close to sbrk base address, but in my environment is +0x10 and you are adding +8. Idk if it's right or no.

**Comment by bata24** [comment] 2024-10-17 17:16
I'm having trouble setting up an ARM64 ubuntu 22.04 environment on Qemu.

The procedure at https://ubuntu.com/server/docs/boot-arm64-virtual-machines-on-qemu stopped midway, so I'm trying other methods.

If you know the construction procedure, could you please tell me?

**Comment by MrNox** [comment] 2024-10-17 19:18
Hey. I'm using a macos m2 as host, and ubuntu as guest :/, sorry. Anyways pwndbg/gef get the address from `tcache` symbol: 
- https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/aglib/heap/ptmalloc.py#L1576 
- https://github.com/hugsy/gef/blob/main/gef.py#L6923

I did same, but the result is: `value has been optimized out`. How can I implement it for your gef fork? Cause it will work for my case.

**Comment by bata24** [comment] 2024-10-17 19:36
>  I'm using a macos m2 as host, and ubuntu as guest :/, sorry

Understood, thanks for the reply.

----

This is the code that emulates the `struct malloc_par`. It returns the address of the `mp_->tcace_bins` member.
https://elixir.bootlin.com/glibc/glibc-2.40.9000/source/malloc/malloc.c#L1890

It only exists to dump `mp_` members, and is not used to dump tcache bins.

```
 3163         @property
 3164         def tcache_bins_addr(self):
 3165             if get_libc_version() >= (2, 26):
 3166                 return self.sbrk_base_addr + self.char_t.pointer().sizeof
 3167             else:
 3168                 return None
```

----

In this GEF, I don't use the `tcache` symbol, I just hardcode the offset. Because I'm assuming there is no symbol.

This is the part that returns the addresses of the tcache bins.
Try modifying the `arch_offset` here.

```
 3774         def tcachebins_addr(self, i):
 3775             if self.heap_base is None:
 3776                 return None
 3777 
 3778             if (is_x86_32() or is_riscv32() or is_ppc32()) and not self.is_main_arena:
 3779                 arch_offset = 0
 3780             elif is_32bit():
 3781                 arch_offset = 0
 3782             else:
 3783                 arch_offset = 0x10
 3784     
 3785             if get_libc_version() < (2, 30):
 3786                 offset = self.TCACHE_MAX_BINS + i * current_arch.ptrsize
 3787             else:
 3788                 offset = 2 * self.TCACHE_MAX_BINS + i * current_arch.ptrsize
 3789             return self.heap_base + arch_offset + offset
```

**Comment by MrNox** [comment] 2024-10-17 19:46
Yes I know it! The error is that the `self.heap_base` address is not the right address for the `tcache`. 

- self.heap_base: 0xaaaaaabff000
- tcache: 0xaaaaaac04010

**Comment by bata24** [comment] 2024-10-17 20:20
Is gef's `self.heap_base` returning the wrong address? If the `sshd` process is not a statically linked binary and has only created one arena, it should match the beginning of the area detected by `vmmap heap`.

```
gef> vmm heap
[ Legend:  Code | Heap | Stack | Writable | ReadOnly | None | RWX ]
Start              End                Size               Offset             Perm Path
0x0000aaaaeb9fc000 0x0000aaaaeba3e000 0x0000000000042000 0x0000000000000000 rw- [heap]
gef>

(This is a Debian arm64 glibc 2.31 environment)
```

If `self.heap_base` is correct and the `tcache` address you obtained by your own investigation is also correct, then that is an environment I did not expect. There is about 0x5000 bytes of space between `self.heap_base` and `tcache` that I did not expect.
Since it is necessary to build the environment to identify and fix the cause, it will take some time.

If you want to fix it immediately in your environment, please add 0x5000 to `arch_offset`.
If this offset changes every time, I can't think of a way to deal with it.

**Comment by MrNox** [comment] 2024-10-17 20:29
this is the output of vmmap:

```
0x0000aaaaaaaa0000 0x0000aaaaaabec000 0x000000000014c000 0x0000000000000000 r-x /opt/openssh/openssh-V_8_9_P1/sbin/sshd  <-  $x30
0x0000aaaaaabfb000 0x0000aaaaaabfe000 0x0000000000003000 0x000000000014b000 r-- /opt/openssh/openssh-V_8_9_P1/sbin/sshd  <-  $x16, $x27
0x0000aaaaaabfe000 0x0000aaaaaabff000 0x0000000000001000 0x000000000014e000 rw- /opt/openssh/openssh-V_8_9_P1/sbin/sshd
0x0000aaaaaabff000 0x0000aaaaaacd2000 0x00000000000d3000 0x0000000000000000 rw- [heap]  <-  $x0, $x19, $x21
...
```
an this the result of `tcache` command:

```
self.heap_base 0xaaaaaabff000
self.heap_base 0xaaaaaabff000
self.heap_base 0xaaaaaabff000
self.heap_base 0xaaaaaabff000
[+] Found 0 valid chunks in tcache.
gef> x/x10xg 0xaaaaaac04010
Invalid number "10xg".
gef> x/10xg 0xaaaaaac04010
0xaaaaaac04010:	0x0007000600070005	0x0001000100010006
0xaaaaaac04020:	0x0007000300070003	0x0007000000010002
0xaaaaaac04030:	0x0001000000070001	0x0007000000010001
0xaaaaaac04040:	0x0001000100000002	0x0003000100000001
0xaaaaaac04050:	0x0001000100020000	0x0000000000000000
gef> 
0xaaaaaac04060:	0x0000000100000000	0x0002000000000000
0xaaaaaac04070:	0x0000000000000001	0x0000000000000000
0xaaaaaac04080:	0x0000000000000000	0x0003000000000000
0xaaaaaac04090:	0x0000aaaaaac978a0	0x0000aaaaaac9ead0
0xaaaaaac040a0:	0x0000aaaaaac9dca0	0x0000aaaaaacb6560
```

I forgot to mention that  it's a `sshd` binary compiled statically by myself.

> In this GEF, I don't use the tcache symbol, I just hardcode the offset. Because I'm assuming there is no symbol.

If you add a try/catch to get the symbol? if it fails then you can get it from `self.heap_base` because the offset +0x10 that you add it is correct.

**Comment by bata24** [comment] 2024-10-17 20:44
When the gdb command gives the error `value has been optimized out`, the symbol address cannot be obtained even through the python API. Is there any way to solve this?

Even if it could be solved, it would be difficult to actually implement.
This is because when in thread A, it would return the address of the tcache of the arena used by thread A.
In other words, while in thread A, it would be impossible to dump the tcache of a different arena used by thread B. (Currently, this is possible)

**Comment by bata24** [comment] 2024-10-17 20:57
Ah, but it would be possible to read the symbol only when there is one thread. I'll try implementing that.

**Comment by bata24** [comment] 2024-10-17 21:22
I've implemented it. Could you please try it with the latest version?
Please let me know if you have any problems.

**Comment by MrNox** [comment] 2024-10-21 12:34
Hey dude sorry for delay, was an off weeknd :).

I tested the last version and have the same result: `value has been optimized out`, I printed the exception:
```
gef> bins
Error getting the tcache address value has been optimized out
------------------------------------------------------------------------- Tcache Bins for arena 'main_arena' -------------------------------------------------------------------------
[+] Found 0 valid chunks in tcache.
-------------------------------------------------------------------------- Fast Bins for arena 'main_arena
```

**Comment by MrNox** [comment] 2024-10-21 13:27
I believe that `__thread` does what you're concerned about. If the execution is standing in a thread, by doing `(void*)tcache`, you will  get the address of the tcache for that thread, right?
https://elixir.bootlin.com/glibc/glibc-2.40/source/malloc/malloc.c#L3125

**Comment by MrNox** [comment] 2024-10-21 15:19
Okay the issue is that you have a command called `tcache`, so it creates conflict with the symbol, I renamed it and works 

```
gef> bins
------------------------------------------------------------------------- Tcache Bins for arena 'main_arena' -------------------------------------------------------------------------
tcachebins[idx=0, size=0x20, @0xaaaaaac04090]: fd=0xaaaaaac97870 count=0
 -> Chunk(base=0xaaaaaac97860, addr=0xaaaaaac97870, size=0x20, flags=PREV_INUSE, fd=0xaaa00061cb67(=0xaaaaaacb67f0))
 -> Chunk(base=0xaaaaaacb67e0, addr=0xaaaaaacb67f0, size=0x20, flags=PREV_INUSE, fd=0xaaa00061a936(=0xaaaaaacb0580))
 -> Chunk(base=0xaaaaaacb0570, addr=0xaaaaaacb0580, size=0x20, flags=PREV_INUSE, fd=0xaaa00061c7f0(=0xaaaaaacb6b40))
 -> Chunk(base=0xaaaaaacb6b30, addr=0xaaaaaacb6b40, size=0x20, flags=PREV_INUSE, fd=0xaaa00061c4a6(=0xaaaaaacb6810))
 -> Chunk(base=0xaaaaaacb6800, addr=0xaaaaaacb6810, size=0x20, flags=PREV_INUSE, fd=0x000aaaaaacb6(=0x000000000000))
tcachebins[idx=1, size=0x30, @0xaaaaaac04098]: fd=0xaaaaaacb06a0 count=0
 -> Chunk(base=0xaaaaaacb0690, addr=0xaaaaaacb06a0, size=0x30, flags=, fd=0xaaa000634610(=0xaaaaaac9eaa0))
 -> Chunk(base=0xaaaaaac9ea90, addr=0xaaaaaac9eaa0, size=0x30, flags=PREV_INUSE, fd=0xaaa00061da9e(=0xaaaaaacb7600))
 -> Chunk(base=0xaaaaaacb75f0, addr=0xaaaaaacb7600, size=0x30, flags=, fd=0xaaa000618c27(=0xaaaaaacb2090))
 -> Chunk(base=0xaaaaaacb2080, addr=0xaaaaaacb2090, size=0x30, flags=PREV_INUSE, fd=0xaaa0006b7df2(=0xaaaaaac1d140))
 -> Chunk(base=0xaaaaaac1d130, addr=0xaaaaaac1d140, size=0x30, flags=PREV_INUSE, fd=0xaaa00063419d(=0xaaaaaac9ed80))
 -> Chunk(base=0xaaaaaac9ed70, addr=0xaaaaaac9ed80, size=0x30, flags=, fd=0xaaa00061a95e(=0xaaaaaacb05c0))
 -> Chunk(base=0xaaaaaacb05b0, addr=0xaaaaaacb05c0, size=0x30, flags=PREV_INUSE, fd=0x000aaaaaacb0(=0x000000000000))
tcachebins[idx=2, size=0x40, @0xaaaaaac040a0]: fd=0xaaaaaac9cd70 count=0


```

**Comment by MrNox** [comment] 2024-10-21 15:44
Now, it doesn't work, same error, weird :s

**Comment by MrNox** [comment] 2024-10-21 15:55
Ok, it works first evaluating the `tcache` symbol and then you can dump the tcache bins, otherwise it doesn't work D:

```
gef> x tcache
'tcache' has unknown type; cast it to its declared type
gef> xx
------------------------------------------------------------------------- Tcache Bins for arena 'main_arena' -------------------------------------------------------------------------
tcachebins[idx=0, size=0x20, @0xaaaaaac04090]: fd=0xaaaaaac97800 count=0
 -> Chunk(base=0xaaaaaac977f0, addr=0xaaaaaac97800, size=0x20, flags=PREV_INUSE, fd=0xaaa000637e17(=0xaaaaaac9d280))
 -> Chunk(base=0xaaaaaac9d270, addr=0xaaaaaac9d280, size=0x20, flags=PREV_INUSE, fd=0xaaa00061c41d(=0xaaaaaacb6880))
 -> Chunk(base=0xaaaaaacb6870, addr=0xaaaaaacb6880, size=0x20, flags=, fd=0xaaa00061c0b6(=0xaaaaaacb6c00))
 -> Chunk(base=0xaaaaaacb6bf0, addr=0xaaaaaacb6c00, size=0x20, flags=PREV_INUSE, fd=0xaaa00061b216(=0xaaaaaacb1ea0))
 -> Chunk(base=0xaaaaaacb1e90, addr=0xaaaaaacb1ea0, size=0x20, flags=PREV_INUSE, fd=0x000aaaaaacb1(=0x000000000000))
tcachebins[idx=1, size=0x30, @0xaaaaaac04098]: fd=0xaaaaaac9ea30 count=0
```

**Comment by bata24** [comment] 2024-10-21 22:37
Is it really a conflict between symbols and commands?
I haven't been able to reproduce this here.
However, just to be on the safe side, I changed the command from `tcache` to `tcachebins`.

**Comment by MrNox** [comment] 2024-10-21 22:41
I don't sure yet, will test it tomorrow, anyway you can remove `if len(GlibcHeap.get_all_arenas()) == 1:`, and test if works for your case.

**Comment by MrNox** [comment] 2024-10-23 15:48
first try debugging sshd:

```
------------------------------------------------------------------------------------------
gef> x tcache
'tcache' has unknown type; cast it to its declared type
gef> tcachebins 
--------------------------- Tcache Bins for arena 'main_arena' ---------------------------
tcachebins[idx=0, size=0x20, @0xaaaaaac04090]: fd=0xaaaaaac97870 count=0
 -> Chunk(base=0xaaaaaac97860, addr=0xaaaaaac97870, size=0x20, flags=PREV_INUSE, fd=0xaaa000637e67(=0xaaaaaac9d2f0))
 -> Chunk(base=0xaaaaaac9d2e0, addr=0xaaaaaac9d2f0, size=0x20, flags=PREV_INUSE, fd=0xaaa00061c46d(=0xaaaaaacb68f0))

```
second try debugging sshd:
```
------------------------------------------------------------------------------------------
gef> tcachebins 
--------------------------- Tcache Bins for arena 'main_arena' ---------------------------
[+] Found 0 valid chunks in tcache.
gef> x tcache
value has been optimized out
gef>
```

As I told you in my last comment, am forcing to use tcache symbol in a test binary that I made (with fews mallocs and frees)
```
            print("arenas %d\n" % len(GlibcHeap.get_all_arenas()))
            print("tcache hex({})\n".format(AddressUtil.parse_address("(void*) tcache")))
```
```
gef> tcachebins 
arenas 1


------------------------------- Exception raised -------------------------------
error: value has been optimized out
```

So for some reason, your script can't allow resolve the tcache symbol, the script "optimize" it. Weird.

**Comment by bata24** [comment] 2024-10-23 23:49
Thank you for your research.
Does this mean that depending on when you execute it, it sometimes works and sometimes doesn't?

If so, could you please test what happens when you run it without gef?
I'm concerned about whether tcache will always be resolved or whether it will be optimized out in some cases.

**Comment by MrNox** [comment] 2024-10-24 12:53
Hey bata24, yes, if first execute `x tcache ` then works, otherwise it doesn't works.

Without gef debugging sshd:
```
Program received signal SIGINT, Interrupt.
0x0000fffff7a6beec in __ppoll (fds=0xaaaaaacbbab0, nfds=102, timeout=<optimized out>, sigmask=0xfffffffff098) at ../sysdeps/unix/sysv/linux/ppoll.c:42
42	../sysdeps/unix/sysv/linux/ppoll.c: No such file or directory.
(gdb) x tcache
'tcache' has unknown type; cast it to its declared type
(gdb) x/xg &tcache
0xfffff7ff5c40:	0x0000aaaaaac04010
(gdb) x/xg (void*)tcache
0xaaaaaac04010:	0x0007000600070005
(gdb) 
```

With my test binary same behavior

**Comment by bata24** [comment] 2024-10-27 01:36
I have investigated from various aspect, but have not been able to identify the cause.
Since I have not been able to determine whether the problem is due to GEF or not, I will postpone the fix indefinitely.
(First of all, I was unable to reproduce this issue in my environment, making it difficult to investigate further.)

**Comment by MrNox** [comment] 2024-10-28 23:34
but in your environment and inside your gef script using first `tcachebin` command, `x/xg (void*)tcache` works?

**Comment by bata24** [comment] 2024-10-29 04:08
I finally reproduced it, thanks.

After isolating the problem, the minimum steps to reproduce are as follows:
```
# NG
root@debian:~# gdb /bin/ls -nx -ex 'b exit' -ex r
...
(gdb) pi gdb.parse_and_eval("(void*)&main_arena")
<gdb.Value object at 0xffffaf796830>
(gdb) p (void*)tcache
$1 = <optimized out>
(gdb) 

# OK
root@debian:~# gdb /bin/ls -nx -ex 'b exit' -ex r
...
(gdb) p (void*)tcache
$1 = (void *) 0xaaaaaaad4010
(gdb) 

# OK
root@debian:~# gdb /bin/ls -nx -ex 'b exit' -ex r
...
(gdb) pi gdb.parse_and_eval("(void*)&_rtld_global")
<gdb.Value object at 0xffffa9a66c30>
(gdb) p tcache
$1 = (void *) 0xaaaaaaad4010
(gdb) 

```

I also found the following:
- Occurs even without GEF
- Occurs only on ARM64 (but i386/x64/ARM32: OK)
- Occurs when evaluating "&main_arena"

Apparently it's a gdb bug, but I'm currently thinking about a solution by GEF side.

**Comment by bata24** [comment] 2024-10-29 06:56
I think it's fixed. Would you like to try the latest version?
I also removed the restriction that tcache symbols can only be used if there is only one arena.

**Comment by bata24** [comment] 2024-11-08 09:27
I think the issue is resolved, so I'm going to close it for now.
Please feel free to reopen if necessary.

**Closed as completed by bata24** 2024-11-08 09:27 UTC
